apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-stack
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.9.9
    chart: loki-stack
    helm:
      parameters:
        - name: grafana.enabled
          value: 'true'
  project: infra
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions: []
