apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    path: infra/network/istiod
    repoURL: 'https://github.com/andersondario/kubernetes-gitops.git'
    targetRevision: dev
  project: infra
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true