apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-management
spec:
  destination:
    namespace: infra
    server: 'https://kubernetes.default.svc'
  source:
    path: infra/namespaces
    repoURL: 'https://github.com/andersondario/kubernetes-gitops.git'
    targetRevision: HEAD
  project: infra-management
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true