apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
  labels:
  name: argocd
  namespace: argocd
spec:
  description: Core Argocd
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
  labels:
  name: microservices-sample
  namespace: microservices-sample
spec:
  description: Microservices-sample Project
  sourceRepos:
  - 'https://github.com/andersondario/kubernetes-gitops.git'
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  - namespace: prod
    server: https://kubernetes.default.svc  
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true