apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-management
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: namespaces
    repoURL: 'https://github.com/andersondario/kubernetes-gitops.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true