apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: api
        imagePullPolicy: IfNotPresent
        name: api
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
        envFrom:
          - secretRef:
              name: api-secrets
