# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: tempo
# spec:
#   destination:
#     namespace: monitoring
#     server: 'https://kubernetes.default.svc'
#   source:
#     helm:
#       version: v3
#     path: infra/monitoring/tempo-distributed
#     repoURL: 'https://github.com/andersondario/kubernetes-gitops.git'
#     targetRevision: dev
#   project: Infrastructure
#   syncPolicy:
#     automated: 
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true