namespace: dev

bases:
- ../../base

patches:
- target:
    kind: Namespace
    name: default-dev
  patch: |-
    - op: replace
      path: /metadata/name
      value: dev
- target:
    kind: ResourceQuota
    name: resource-quota
  patch: |-
    - op: replace
      path: /metadata/name
      value: quota-prod
    - op: replace
      path: /spec/hard/requests.cpu
      value: 2
    - op: replace
      path: /spec/hard/requests.memory
      value: 2Gi
    - op: replace
      path: /spec/hard/limits.cpu
      value: 4
    - op: replace
      path: /spec/hard/limits.memory
      value: 4Gi
    - op: replace
      path: /spec/hard/pods
      value: 10
- target:
    kind: LimitRange
    name: limit-range
  patch: |-
    - op: replace
      path: /metadata/name
      value: limit-dev